package io.casehub.desiredstate.api;

public enum FaultType {
    NODE_DESTROYED, NODE_DEGRADED, PROVISION_FAILED, DEPROVISION_FAILED,
    SUSPEND_FAILED, RESUME_FAILED,
    HUMAN_NODE_TIMEOUT, DEPENDENCY_UNAVAILABLE, APPROVAL_REJECTED,
    PLAN_REJECTED
}
